[tox]
envlist = py312
isolated_build = true

[testenv]
deps =
    pytest
    pytest-cov
    pytest-asyncio
    pytest-xdist
allowlist_externals = uv
commands =
    uv run pytest -n auto {posargs:tests}
